// this select tag was based off of code generated by Gemini-2.5-pro
// with the prompt: generate me a dumb kiss native html select component in react

import React, { useEffect, useState } from "react"
import { backendURL } from "../constants"

function DatePicker({ phantomRowIEdit, phantomRowIEditHeader}) {
  // Code generated by Gemini-2.5-pro
  // Function to format a Date object to 'YYYY-MM-DD'
  // using prompt: convert date to 'YYYY-MM-DDTHH:mm:ss.sssZ'
  const formatDateForInput = (dateObj) => {
    if (!dateObj) return '';
    // .toISOString() returns 'YYYY-MM-DDTHH:mm:ss.sssZ'
    // We just need the first 10 characters.
    return dateObj.toISOString().slice(0, 10);
  };

  // State to hold the currently selected value
  const [date, setDate] = useState(new Date(phantomRowIEdit[phantomRowIEditHeader])) // Default to the placeholder
  console.log(date)


  // This function is called whenever the user changes the selection
  const handleChange = (event) => {
    const tDate = new Date(event.target.value)
    setDate(tDate)
    phantomRowIEdit[phantomRowIEditHeader] = formatDateForInput(tDate)
    
    console.log("Selected:", event.target.value)
  }

  return (
        <input
            className={` text-sm place-self-center w-full h-full m-0 p-inherit border-none font-mono box-border resize-none absolute `}
            type="date"
            id="start"
            name="date"
            value={formatDateForInput(date)}
            onChange={handleChange}/>

  )
}

export default DatePicker
